### ISSUE TITLE
Decouple motion from frameTime (Higher FPS)

### ISSUE THREAD

**Issue by dcwatson** [avaraline/Avara#11]
Right now, updates happen every 64ms (frameTime). None of the frame actions take into account how long the frame actually is, since it was hard-coded in Avara. So trying to run the game at shorter frame times (for better network performance, higher FPS, etc) works, but results in speeding up the whole game - movement is much faster since the same movements happen in shorter times, gravity feels stronger, etc.

This is a pretty big task, since it touches a LOT of the game code, and has implications for LT handling. It's not as critical now that the game loop has been refactored so events and rendering can happen more than once per frame. We may even decide 64ms is still the "right" frameTime for now, but decoupling it would open up some options.

**Comment by doomlaser** [comment]
opened up an issue on similar lines. Just saw this. I would love to see this game running at 60fps..

**Comment by assertivist** [comment]
@doomlaser 

changing the frame timing has a lot of implications on gameplay, as a lot of the physics and animations are very simple calculations expecting a constant framerate (do a search for "frametime" in this repo to see what i mean)

This isn't to say that we haven't been working on this. There is a 'testing' branch that you can check out. This branch has a few automated tests set up to show that certain calculations have been changed to be framerate independent. It's just a question of finding every single spot there is a framerate dependent calculation and replacing it with an independent equivalent (and writing tests to make sure).

If you want to try it out, change the "frameTime" instantiation value in CAvaraGame.h. 64 is the old game's frametime, you can make the game faster by lowering this number. I believe a value of 16 would give you 60FPS.

**Comment by rherriman** [comment]
I was just responding to this myself. But yes, this issue will take a lot of work to get operating, at least at a level that we feel good about. The first order of business is refactoring a significant amount of code to make it possible to test (@jonathan-voss did a lot of this work already), then write tests for every projectile/AI/logic object/etc. at the original framerate so we can be sure we won't deviate too far from the original outcomes. _Then_ we can take a crack at updating their calculations to be independent from frametime, and write even more tests at additional framerates to make sure they fall within some narrow threshold of the original value.

Unfortunately identifying every moving part that needs testing and actually writing tests is not particularly fun or sexy work, so it hasn't been worked on for awhile... plus, people are busy!

**Comment by assertivist** [comment]
Update on this: The tests and basic framework for changing the framerate have now been merged into 
master with #38

**Comment by assertivist** [comment]
Sorry for the comment spam--the easiest way to play with it is here: https://github.com/avaraline/Avara/blob/master/src/game/CAvaraApp.cpp#L58

Change this `64` constant to a different number. 1000 divided by this number is the FPS: 

- 64 for the original 15.625 FPS
- 32 for 31.25 FPS
- 16 for 62.5 FPS <-- the final goal

We've made progress as far as the amount of things Avara is doing to render a given frame, so this should be achievable relatively easily. If you run `make/tests` and then `build/tests` you can see the gameplay elements that have already been fixed so that they scale with this frametime. Lots of things are still not scaled, you'll notice that jumping in particular will make you fly very far at lower values.
