### ISSUE TITLE
Move latency settings to Server section and gray out for clients

### ISSUE THREAD

**Issue by tra** [avaraline/Avara#114]
It appears that only the server settings for latency have any affect on a game so they should be in the Server nanogui element.  Also, they should be grayed out for the clients (but the latency value should still be allowed to change as LT changes).

**Comment by assertivist** [comment]
![image](https://user-images.githubusercontent.com/1486313/100824158-7f00ac80-340a-11eb-821d-206dd2dd6e47.png)
