### ISSUE TITLE
Incarnator availability problem

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#116]
I remember this bug from the original!
https://photos.app.goo.gl/vAssTKY7NY6oY82W7
Interesting things to note:
* I was technically not in limbo, because I could self destruct and see the message "Self destruct activated"
* Then I would return to limbo and it would stop
* When the timer for respawn triggered it would start happening again

**Comment by tra** [comment]
when it happened to me i was in a medium hull, not sure if that matters

**Comment by rherriman** [comment]
If I recall correctly the issue seems to occur when multiple players die in the same frame. I streamed the game when it happened to you, may be worth checking out to see if that was the case.

**Comment by assertivist** [comment]
twitch clip of aforementioned occurence https://clips.twitch.tv/HedonisticAmorphousPangolinVoHiYo
unfortunately it looks like no one else died at the same time :/

**Comment by assertivist** [comment]
youtube mirror in case twitch eats my clip https://youtu.be/znN-6EbuA88

**Comment by tra** [comment]
I think it happened on the death after that clip.

**Comment by assertivist** [comment]
There are two deaths in the clip--its the second one where I kill you and
push ryan really far towards the end is the point where it happened i think
(well at least, that's when you type 'whoa')

**Comment by tra** [comment]
Oh yes, my bad, "whoa" was in response to me having a teleporter acid trip.
