### ISSUE TITLE
PICT parsing error in Target

### ISSUE THREAD

**Issue by ahalstead-sctg** [avaraline/Avara#123]
Need someone to confirm this one on the original. But it looks like there is a block missing in the level "Target" of AA Deux.

![2020-08-21-223450_2560x1080_scrot](https://user-images.githubusercontent.com/68553843/90949629-92a97980-e3fe-11ea-8dc5-54fad5e2b814.png)

**Comment by shrizza** [comment]
![Picture 7](https://user-images.githubusercontent.com/18588498/91072956-3f8d2c00-e675-11ea-9104-ee7f14af8725.gif)

**Comment by assertivist** [comment]
closing -- confirmed this bug in the original
