### ISSUE TITLE
Level load race condition

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#127]
There seems to be issues when two people load a level simultaneously. It may be because the other player's game is busy loading geometry into the simulation while the other person sends the load level command. In any case, it seems to put one player's game into a strange state where they always show "level not found" as a status.

**Comment by tra** [comment]
Server should arbitrate what is loaded.  It might mean we need a new command, something like kpRequestLevelLoad and only the server can do the kpLoadLevel command.

**Comment by assertivist** [comment]
https://github.com/avaraline/Avara/blob/b5e4e5c8fd8df3e71a404896ef9b06e253d6c5f7/src/gui/CLevelWindow.cpp#L25
https://github.com/jmunkki/Avara/blob/d02cd0da4a4a13d72a63811cba220a9dd415dcad/src/Avara/Game/CNetManager.c#L1621

We could easily expand the existing PermissionsQuery for this. It would mean adding to the crusty UI possibly, but only a couple checkboxes or so.

**Comment by tra** [comment]
I have fixed this on the `commands` branch with commit 4edef43.  Will close this issue when it has merged to master.
