### ISSUE TITLE
Destroy character of players who disconnect and are kicked

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#141]
@tra added code to the game that kicks out players that disconnect or have connections worse than a certain threshold. Currently when this happens, the player character for that player stays in the game, unpiloted. Instead, when this happens, `DoExplode` or the same code that runs when an Abort occurs, should also run in the next frame after the kick

**Comment by tra** [comment]
The code to kick players out was a bit of an experiment to see if it would stabilize the game when a player had a bad connection.  We could also roll back this change?  I wouldn't be offended either way.

**Comment by assertivist** [comment]
It hasn't been triggered inappropriately in a long time. The last time i saw it happen, someone had just closed the window accidentally. And it was better for the other players, to keep playing, than to have the game stop and try to send packets to that person anyway. So that should stay! I just though it was a easy bit of cleanup that someone could do, to clean up the shell that gets left behind. It kinda messes with the game a little bit because you can use the empty character as cover from missile locks (it will still have the targetable flag set).

**Comment by rherriman** [comment]
Unresponsive users are no longer auto-kicked. I believe we can close this issue.

**Comment by tra** [comment]
Agreed and closed.
