### ISSUE TITLE
Slivers only collide with the ground

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#15]
![sliver collisions](https://user-images.githubusercontent.com/1486313/45374088-592f2900-b5ae-11e8-854d-d6d850b54063.gif)
Slivers on the ground have a nice bouncy effect but when slivers hit level geometry they just fall through.

**Comment by dcwatson** [comment]
Turns out this is how Avara worked, too. Doesn't seem worth the code/processing to make these collisions "real".
