### ISSUE TITLE
Field object not working correctly

### ISSUE THREAD

**Issue by biggnome** [avaraline/Avara#152]
I noticed an issue in Boake Maze wherein a floating block is erroneously created in one of the rooms, intersecting with a ramp which is not present in the original game. (The player can get pinned beneath it requiring a reset.) I've looked at the level PICT, and while I'm not too familiar with the format, it seems to me port may be incorrectly parsing a field as a wall.

![boake](https://user-images.githubusercontent.com/12508219/107279393-d83d1b80-6a0b-11eb-84a2-7dbc406808a1.png)

**Comment by assertivist** [comment]
Thank you for the _excellent_ report. There's other problems with fields in this set, one area of Heimdall is supposed to have trampolines that don't work. Additionally, the "force fields" in training grounds do not work correctly and there's something funny with Fort of Bob as well. We're looking into it and appreciate test cases like this!

**Comment by biggnome** [comment]
No problem. I haven't noticed anything unusual about either of those levels (apart from a once-upon-a-time overly conservative out of bounds condition in Fort of Bob, but that was fixed ages ago), although I can confirm re: the Heimdall trampolines--there's a cartoon "boing" sound triggered by the fields' associated 'flyOn' message that doesn't play in the ported version, which at the very least suggests that the whole field element is being ignored, but I'm sure I'm not telling you anything new.

I spotted a couple of other bugs on Bomb Deposit as well (awesome that the case sensitivity thing I brought up recently got fixed so quickly, by the way!)--namely, the destructable grate initially spawns underneath the player rather than in the alcove behind (I notice the PICT file has the line "shape = bspGrid7" overlapping the little arc for the Incarnator--maybe these are being parsed as occupying the same position?); and once the "@oGdoor"--another field, I notice--is in its retracted state, the player can get 'sucked in' to it, requiring a reset if they enter too close by. Can't make heads or tails of that one I'm afraid, except to note that tolerances in this level are ridiculously tight, making it tricky to navigate even in the native version--I wonder if the player may be getting partially stuck inside the architecture or something? Purely just guessing though.

**Comment by rherriman** [comment]
I do want to mention that the problems in Training Grounds and Fort of Bob are _speculated_ to be field related, but we don't know for sure. Rather than simply not appearing (or manifesting as blocks), there seem to be large, extremely powerful fields where there previously weren't any. Clearly there are some PICT parsing issues at play, here, but whether or not these will all be solved by the same fix is unclear at this time.

**Comment by rherriman** [comment]
https://www.twitch.tv/videos/636108043

Demonstrated here, though there also seems to be a strange warping issue, too. Haven't tested this for awhile so unclear if it still behaves this way.

**Comment by dcwatson** [comment]
The issue with Heimdall seems to be the ramps are placed at `y=0`. Setting them to `y=0.1` makes them work. Will need to look at whatever should be calling `CAbstractActor::StandOn` (which fires the stepOnMsg) and figure out why it isn't.

**Comment by assertivist** [comment]
> The issue with Heimdall seems to be the ramps are placed at `y=0`. Setting them to `y=0.1` makes them work. Will need to look at whatever should be calling `CAbstractActor::StandOn` (which fires the stepOnMsg) and figure out why it isn't.

https://github.com/avaraline/Avara/blob/ae0cef53bb9deb97ef153b039222f266741d7956/src/game/CWalkerActor.cpp#L347-L367

There are other leg related bugs: #19 

It may just be that someone needs to spend some quality time with the legs, they are also very frame rate dependent.

**Comment by dcwatson** [comment]
That last change should address some of the field issues, specifically with Heimdall trampolines.
