### ISSUE TITLE
Legs and Head don't move while crouched and walking backwards on any block

### ISSUE THREAD

**Issue by ryansommers** [avaraline/Avara#19]

**Comment by dcwatson** [comment]
That last change should address this. Will need to play test.

**Comment by shrizza** [comment]
This seems resolved now. Close?

**Comment by assertivist** [comment]
I would like to hear from @ryansommers , BUT I can't reproduce this anymore!

**Comment by ryansommers** [comment]
I can't reproduce either, think this one is fixed.
