### ISSUE TITLE
jump vs super jump redux

### ISSUE THREAD

**Issue by tra** [avaraline/Avara#208]
PR #189 fixed a "problem" with jumping that made sure the crouch wasn't cut in half before calculating jump velocity.  Unfortunately, this fix seems to have made it so that all jumps are now "super jumps" and the old single-key regular jump is gone.

Let's get into the code.  Here's a snippet of code from before the fix:

        if (TESTFUNC(kfuJump, ft->down)) {
            crouch += (stance - crouch - MINHEADHEIGHT) >> 3;
        } else if (TESTFUNC(kfuJump, ft->held)) {
            crouch += (stance - crouch - MINHEADHEIGHT) >> 2;
        } else {
            crouch >>= 1;
        }

        if (TESTFUNC(kfuJump, ft->up) && tractionFlag) {
            speed[1] >>= 1;
            speed[1] += FMulDivNZ((crouch >> 1) + jumpBasePower, baseMass, GetTotalMass());
            jumpFlag = true;
        }

What this code is doing is testing whether the jump key is being pressed down, held down, or lifted up and acting accordingly.  When it's being pressed and/or held down then the code increases the `crouch` variable so that it approaches the value of `stance-MINHEADHEIGHT`.  In other words, the effect is to push the HECTOR down to `MINHEADHEIGHT`.  Then, when the jump key is lifted up, the last conditional computes the upward velocity (`speed[1]`) based on the `crouch` value.  So far so good.

The tricky part of this is that, when the jump key goes up, the `crouch` variable is cut in half in the `else` block above where it does `crouch >>= 1`.  For example, if the jump key is held down for a long time, maybe the `crouch` amount equals `50000`.  Then when the jump key is released the `crouch` variable is cut down to `25000` before being used in the upward velocity calculation.  This is/was the standard calculation for jump, or just a "regular jump".

But over the years, some smart players figured out that if you "glissando" several jump keys while jumping, then you could jump higher.  What was actually happening was that the pressing of multiple jump keys would increase the likelihood that a jump key was being pressed in the same frame as another jump key was being released.  In the code snippet above is, this would cause the execution of the code to **not** reduce the `crouch` before computing the jump velocity (it would pass the first conditional).  Thus the jump velocity would be higher and hence was born the "super jump".

Recently I fixed the jump calculation because there was another problem associated with this code.  The other problem was that if you had keyboard repeat turned on, sometimes you would get a regular jump and sometimes you would get a super jump depending on whether the keyboard repeat inserted a "jump key down" into the same frame as when the jump key was released up.  But the net effect of this fix is that now all jumps are effectively super jumps.

## The Fix / Proposal

Now we need to restore the ability to do both regular and super jumps in such a way that it works equally across different frame rates.  First of all, we can fix the keyboard repeat rate by detecting if a `SDL_KEYDOWN` is from a repeat or not.  I have played with this and think we can eliminate the key repeat programmatically, no problem there.

But the problem with the "glissando" technique is that it requires a keyDown to be placed into smaller and smaller frames.  This would mean that you'd potentially have to be really fast with the keys for higher frame rates and that inconsistent behavior is what I'd like to address.

My proposal is that we do something a little different and predictable.  For example, what if we define another key, say `JumpBoost` that's pretty much a meta key for jumping?  If the `JumpBoost` key is pressed during a jump then you get the super jump.  If not, you get the regular jump.  This would be easier to implement and easier to use though it might require some people to change how they jump.  I suppose you could even assign both functions to one key if you'd like to have one for super, and another for regular jumps.

What do you think?

**Comment by rherriman** [comment]
I think the issue with the jump modifier approach is that it doesn't really add anything in terms of gameplay, provided it works like every other key-mappable action where you can assign multiple actions to a key.

In this scenario, yes, we could maintain the distinction between normal jumps and super jumps, and it could even mimic the glissando movement somewhat...but what is more likely to happen is that people will have a normal jump key and a super jump key (thanks to mapping jump and the jump boost to the same key), _or_ even more likely, not use a normal jump key at all. Which is essentially the status quo where everything is a super jump.

If the point of breaking up the two jump types is also to re-increase the skill ceiling (with super jumps requiring some sort of practice to produce reliably), being able to just have one key activate a super jump also fails to meet this goal, unfortunately.

**Comment by tra** [comment]
> I think the issue with the jump modifier approach is that it doesn't really add anything in terms of gameplay, provided it works like every other key-mappable action where you can assign multiple actions to a key.
> 

I was thinking maybe we could code it so that the super jump would only occur if the modifier key is in the Held state while the jump key is Up.  The way the code currently works is when a key is `Up` it is simulatanesously removed from the `Held` list.  In that case, mapping them both wouldn't work.  The user would still have to press 2 keys thus making still something for a more skilled player to pull off... not as hard as the glissando but at least harder than a regular jump and, more importantly, repeatable.

**Comment by tra** [comment]
One more thought, this might also be "compatible" with the glissando technique.  In other words, if you mapped the extra jump keys to JumpBoost (or JumpModifier?), then I *suspect* you could still play the way you're used to playing now to get the super jump.

**Comment by ryansommers** [comment]
> I was thinking maybe we could code it so that the super jump would only occur if the modifier key is in the `Held` state while the jump key is `Up`....The user would still have to press 2 keys thus making it something for a more skilled player to pull off... not as hard as the glissando but at least harder than a regular jump and, more importantly, repeatable.

That sounds right to me.

**Comment by rherriman** [comment]
Checking for the held state specifically could work, yeah. I kind of wonder if we even need a "jump boost" action, though! Maybe we just check to see if jump is being held down _and_ released (because multiple buttons are mapped to jump as before).

**Comment by ryansommers** [comment]
Right, seems like two separate jump buttons would work rather than a specific modifier? Assigning multiple jumps to one button wouldn't matter, you'd need two separate jump buttons so one can be held down while the other is released.

**Comment by tra** [comment]
> Checking for the held state specifically could work, yeah. I kind of wonder if we even need a "jump boost" action, though! Maybe we just check to see if jump is being held down _and_ released (because multiple buttons are mapped to jump as before).

The problem I have with checking for both `keysDown[jump]` and `keysUp[jump]` is that it requires them to be both true in the same frame.  Currently `keysUp` is only true for the single frame when the key is released.  What that means is that you would have to press a key in the exact same frame you are releasing another key.  I was looking for a mechanism that doesn't rely on that timing which would vary for different frame rates.  And keeping track of **when** a button is released seems like a lot of extra code complication for little gain.

**Comment by tra** [comment]
> Right, seems like two separate jump buttons would work rather than a specific modifier? Assigning multiple jumps to one button wouldn't matter, you'd need two separate jump buttons so one can be held down while the other is released.

Similar to my reply above, the current code doesn't keep track of all the individual keys per se.  It maps the keys by function (e.g. `jump`) and it is event driven.  So when a jump key is pressed down it adds that to both `keysDown[jump]` and `keysHeld[jump]`.  And when a jump key is released it adds it to `keysUp[jump]` and **removes** it from `keysHeld[jump]`.  Therefore, you can't currently keep track if one jump button is held down and the other is being released because as soon as **any** jump button it is also removed from the `keysHeld` mapping.  Reworking this to keep track of every possible jump key would be a fairly significant overhaul of how the code works because the mapping is just a 4-byte bit-mapped integer right now.

So you can see why I settled on defining another key.  Because you **can** keep track if another key function `jumpBoost` is being held down while the `jump` key is being released.

**Comment by tra** [comment]
@rherriman and I discussed this further and settled on the idea that you should be able to do it with multiple `jump` keys and not add a new key type (`jumpBoost`).  So the proposed solution is as follows:

If one `jump` key is being held while another `jump` key is being released, then it will result in the enhanced jump (super jump).  This will require a change to how the jump event is mapped/tracked, perhaps a one-off for jumping (TBD).

**Comment by tra** [comment]
The branch named `fix-jump2` contains the proposed fixes and restores the old "regular" jump and makes it less "floaty".
