### ISSUE TITLE
NAT Punchthrough

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#209]
For new players, it is nearly impossible to get into a game by hosting a server, as most firewalls (correctly) discard incoming UDP connections from random addresses.

A solution to this problem is NAT Punchthrough. Basically, the user behind the firewall attempts a connection via UDP to the server and other clients, which lets the user's firewall know that they are accepting UDP traffic from those hosts. 

Then, when responses or other connections come in, the packets will get forwarded accordingly.

This will require the user's client to know the other addresses attempting to connect to them. The only way to set this up is to have the tracker keep note of all the external addresses/ports of people trying to play on a specific server. That way, when the tracker is queried, the connections can all be attempted and ports will be open on the firewall before the game attempts communication with other clients or the server. This means that either the server or the clients need a way to tell the tracker that a new user plans on joining a tracked game, so that the tracker knows which addresses to send and when.

When a server is added to the tracker, keep track of its external address and port
When the user selects a server on the tracker, the tracker must not only give the selected server's address and port, but also the address and port of all connected users
The user will open connections with all the connected user and the server to allow incoming traffic.
The tracker will add the new user's external address and port to the list of addresses/ports for any other subsequent users to consume.

**Comment by tra** [comment]
I think Dan's turnip server mods take care of this right?
