### ISSUE TITLE
lookRight broken with light hull

### ISSUE THREAD

**Issue by tra** [avaraline/Avara#210]
The light hull has big cheeks that are hard to see around during lookLeft & lookRight.  But lookRight seems to have a partially transparent cheek.  Attaching video.

https://user-images.githubusercontent.com/4057/150617971-77e64863-423e-4989-b7ad-fec9cd89221c.mov

This doesn't seem to be an issue with the medium or heavy hulls, mostly because the view is different for those hulls.

**Comment by assertivist** [comment]
Closed in #221
