### ISSUE TITLE
Mouse issues in Linux

### ISSUE THREAD

**Issue by havoc-viper** [avaraline/Avara#23]
Thanks for porting this game! I have kicked myself ever since I sold our last Mac, so found your port the best Christmas present ever. ;)

There are some issues, though.

Compiled Avara in VirtualBox 6.0.0 VM running Ubuntu 18.10, on a Windows 10 OS.
Using SDL2-2.0.9 and SDL2_net-2.0.1. Wonder if all the below problems could be solved if I compiled for Windows natively, but don't know how to do that. Any instructions posted along that line to the github repository would be welcomed.

1. Interface to launch a game is very slow--it is as though the mouse processing is incredibly laggy. You have to wait 10 seconds or more for the interface to recognize the mouse is over a particular button.
2. Once a level is loaded and started, when the HECTOR is instantiated, using the mouse to turn the hull's head looks like it either tracks along an arbitrary axis (so the hull faces up-ish or down-ish, for instance), or it tracks too sensitively, overshooting where it should point. It acts laggy as you try to correct for the over-shoot, so it takes patience to line vision up with the HUD-V.

Once the level is loaded, you can run around and fire weapons with no problem or lag, but the mouse control is very difficult. I can't get audio to work, either, but I'll worry about that later.

**Comment by rherriman** [comment]
Compiling on Windows is a bit of a pain as I understand it, you could try a native Windows build here: http://avaraline.net/dev/builds/

Not a solution to the issue, but I haven’t heard this one yet and I know some people have compiled and ran it on Linux without this issue. Perhaps they can weigh in, but I’m guessing more information is needed.

**Comment by dcwatson** [comment]
I don't know how VirtualBox typically handles mouse warping, but I know that was always the main issue (or one of them anyway) when trying to play classic Avara in an emulator. As for performance, I don't know how much 3D acceleration VirtualBox does for a Linux guest on a Windows host. In any case, you're definitely better off running a native Windows build on Windows, or booting into Linux to run a native Linux build if that's more your speed. Let us know how the Windows build Ryan linked above works for you!

I'm going to close this, as I suspect these issues are due to running in VirtualBox, and not Linux-specific issues (we have at least one person developing/running on Linux).

**Comment by havoc-viper** [comment]
The WinAvara worked great on my Windows 10 box, but not on the Windows 7
one. This was definitely a Linx/VirtualBox thing.

Mouse control, audio, general action is beautiful on the Windows 10
box--feels like the real thing. It did crash unexpectedly on Net '99 Intro,
though. The first time I ran it, it just crashed; the second time, in the
cmd tool it repeatedly spewed out "Error 00000502 after convex fill" in an
infinite loop without the level loading. I saw the same thing with Barantu
in the-codex, but the level still played, but continued to spew the errors
even after I self-destructed the HECTOR.

If this kind of info is helpful, I'll gladly load levels and see what
happens, and forward any errors I see to you. Otherwise, I'll just leave
you devs alone to work your magic. ;)

Haven't tried any networking yet, but I'll get to it once I wipe the tears
of joy from my eyes.

Very impressive--can't thank you enough for the great work and for bringing
Avara back to me. :D

**Comment by havoc-viper** [comment]
Awesome. Thank you! A couple more questions...

Is there a way to configure the keyboard with commands like in the old Mac
version? I vaguely recall a way to bring up a keyboard map and move icons
around.

Is it possible to port more level sets into the game? Have the devs got a
method for doing that or is it a painfully, protracted process?

**Comment by rherriman** [comment]
It is possible to change the key mapping but there is no UI for it right now. You have to modify the `prefs.json` file directly. On Windows, it looks like it's at `C:\Users\<your_user>\AppData\Roaming\Avaraline\Avara\` but I can't verify that myself.

Here's a list of the valid keycodes to use: https://wiki.libsdl.org/SDL_Keycode

It is possible to port more levels, yes, but it is equal parts "simple" and "complicated." For most sets, it is mostly just a matter of extracting the resource fork and putting it in the right place... though I don't recall off the top of my head whether the level set menu in the game is hard-coded or not. Sets with custom BSPs are more problematic, the BSP data has to be converted to a new format. I'm not entirely sure what's involved there, @dcwatson and @assertivist would know more about that. An existing issue arises from the fact that many sets used the same IDs for their custom BSPs. The port currently doesn't handle that well, and thus frequently will crash when attempting to load a level with a custom BSP in it.

We have had plans to eventually change the level format to something more easy to work with in modern times. @assertivist did a lot of work on a PICT to SVG converter, for example. (Switching to an SVG format would also make it easier to edit and create new levels via Inkscape, eliminating the need to set up an emulator to run ClarisWorks 4...)

We also have had plans to build a web service to distribute level files and other assets, rewrite the level loading (and related UI) to consume that web service, and then bulk convert every level set we have in our possession (which is a pretty comprehensive collection). @dcwatson built out an early version of the asset server, but it isn't being used by Avara, yet.

**Comment by havoc-viper** [comment]
Hi guys,

I revisited the Avara port again and wondered if you had advice for running
a *local* server. A buddy of mine and I are on the same home network, and
we can see each other's servers, but can't connect to them to get a game
going. We aren't trying to go out to an external server so I didn't think
the writeup in the wiki applied to us.

I tried the port forwarding recommendations in the Avara wiki just to see
if that was the magic we needed, to no avail. Just wondered if you had any
suggestions.

Thanks again for all you work in porting this--Avara was always my favorite
game. ;)

**Comment by assertivist** [comment]
Yo Havoc! The instructions, and also the tracker itself, are purely for internet games. To host locally, you'll need to find your computers local IP address. It should look like 192.x.x.x or 10.x.x.x --give that to your friend and have him type it into the server address field manually. 

On windows you can open CMD.exe and enter "ipconfig" to get your local address
