### ISSUE TITLE
/l with no arguments segfaults.

### ISSUE THREAD

**Issue by dcwatson** [avaraline/Avara#272]

**Comment by assertivist** [comment]
` std::allocator<char> > > >&&) (__functor=..., __args=...)
    at C:/msys64/mingw64/include/c++/12.2.0/bits/std_function.h:290
#6  0x00007ff718519edf in std::function<bool (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)>::operator()(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) const (this=0x2e88aa01b30,
    __args=std::vector of length 0, capacity 0)
    at C:/msys64/mingw64/include/c++/12.2.0/bits/std_function.h:591
#7  0x00007ff71840dc99 in TextCommand::ExecuteMatchingCallbacks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)::$_0::operator()(TextCommand*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) const (this=0xf77c7fede0,
    command=0x2e88aa01af0, cmd="/l", vargs=std::vector of length 0, capacity 0)
    at src/tui/TextCommand.cpp:69
#8  0x00007ff71840dbd6 in std::__invoke_impl<bool, TextCommand::ExecuteMatchingCallbacks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)::$_0&, TextCommand*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >(std::__invoke_other, TextCommand::ExecuteMatchingCallbacks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)::$_0&, TextCommand*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&) (__f=..., __args=..., __args=..., __args=...)
    at C:/msys64/mingw64/include/c++/12.2.0/bits/invoke.h:61
#9  0x00007ff71840db1a in std::__invoke_r<bool, TextCommand::ExecuteMatchingCallbacks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)::$_0&, TextCommand*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >(TextCommand::ExecuteMatchingCallbacks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)::$_0&, TextCommand*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&) (__fn=...,
    __args=..., __args=..., __args=...) at C:/msys64/mingw64/include/c++/12.2.0/bits/invoke.h:114
#10 0x00007ff71840d9f9 in std::_Function_handler<bool (TextCommand*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >), TextCommand::ExecuteMatchingCallbacks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)::$_0>::_M_invoke(std::_Any_data const&, TextCommand*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&) (
    __functor=..., __args=..., __args=..., __args=...)
    at C:/msys64/mingw64/include/c++/12.2.0/bits/std_function.h:290
#11 0x00007ff718519e03 in std::function<bool (TextCommand*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)>::operator()(TextCommand*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) const (this=0xf77c7fede0,
    __args=std::vector of length 0, capacity 0, __args=std::vector of length 0, capacity 0,
    __args=std::vector of length 0, capacity 0)
--Type <RET> for more, q to quit, c to continue without paging--
    at C:/msys64/mingw64/include/c++/12.2.0/bits/std_function.h:591
#12 0x00007ff71840d3ba in TextCommand::FindMatchingCommands(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool (TextCommand*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)>) (fullCommand="/l", matchCb=...)
    at src/tui/TextCommand.cpp:54
#13 0x00007ff71840d506 in TextCommand::ExecuteMatchingCallbacks (fullCommand="/l")
    at src/tui/TextCommand.cpp:66
#14 0x00007ff71840568f in CommandManager::ExecuteMatchingCommand (this=0x2e88a9a9a20,
    chatText="/l", player=0x2e8828abeb8) at src/tui/CommandManager.cpp:87
#15 0x00007ff71837fb61 in CPlayerManagerImpl::RosterMessageText (this=0x2e8828abeb0, len=0,
    c=0x2e88b3cb959 "\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r"...) at src/game/CPlayerManager.cpp:789
#16 0x00007ff71836ad41 in CNetManager::ReceiveRosterMessage (this=0x2e8828aaba0, slotId=0, len=1,
    c=0x2e88b3cb958 "\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272\r\360\255\272", <incomplete sequence \360\255\272>...) at src/game/CNetManager.cpp:371
#17 0x00007ff7183f3e34 in CProtoControl::DelayedPacketHandler (this=0x2e8828aaf40,
    thePacket=0x2e88b3cb940) at src/net/CProtoControl.cpp:92
#18 0x00007ff7183f3a78 in DelayedProtoHandler (thePacket=0x2e88b3cb940,
    userData=0x2e8828aaf40 "\350\071c", <incomplete sequence \367\177>)
    at src/net/CProtoControl.cpp:40
#19 0x00007ff7183eb067 in CCommManager::ProcessQueue (this=0x2e88b371a50)
    at src/net/CCommManager.cpp:366
#20 0x00007ff71836a16d in CNetManager::ProcessQueue (this=0x2e8828aaba0)
    at src/game/CNetManager.cpp:203
#21 0x00007ff718345613 in CAvaraGame::GameTick (this=0x2e8828a9510) at src/game/CAvaraGame.cpp:844
#22 0x00007ff7183368e7 in CAvaraAppImpl::idle (this=0x2e88283eef0) at src/game/CAvaraApp.cpp:148
#23 0x00007ff7184509cc in nanogui::mainloop (refresh=4) at vendor/nanogui/common.cpp:84
#24 0x00007ff7184afe9e in SDL_main (argc=1, argv=0x2e880e8c530) at src/Avara.cpp:106
#25 0x00007ff7184b186e in main_getcmdline ()
#26 0x00007ff7183012ee in __tmainCRTStartup ()
    at C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:272
#27 0x00007ff718301406 in mainCRTStartup ()
    at C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:193
`

**Comment by tra** [comment]
We should try all commands without arguments when fixing this.
