### ISSUE TITLE
Chat shouldn't depend on window focus

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#32]
I ghetto-rigged a system together that requires you to hover over the chat window in order to type in it, so that I don't steal focus from the other text boxes in the UI. We should figure out a way to make the chat box the default for handling text input unless you actually click into the other text fields (like server, tracker, etc.)

**Comment by assertivist** [comment]
reported by @shrizza

**Comment by blenkush** [comment]
fixed awhile ago
