### ISSUE TITLE
How to import levels?

### ISSUE THREAD

**Issue by thegagne** [avaraline/Avara#37]
Hey, original author of level "Chut" here (aka DudyPowder). I've found my old map on-line, how do I play it in here?

I made a bunch of maps back in the day but haven't found them all...

Some memorable stuff:
- A working jukebox with some old .wav files for music.
- I figured out how to rotate ramps to make "corner" pieces and made some levels with "rounded" terrain.

**Comment by assertivist** [comment]
We're still working on converting to a new format from the old resource fork stuff. So at the time you extract a resource fork file from your level, put it in the `levels` folder with a `.r` extension, and then add it here: https://github.com/avaraline/Avara/blob/master/src/gui/CLevelWindow.cpp#L9

To make a `.r` file, you have to get the level file into OSX, and open the command line. Then you can do `cp <LevelSetFile>/..namedfork/rsrc <LevelSetFile>.r` and that is what you want to drop in the `levels` directory.

This isn't super ideal, but it's the only way to add sets currently. Feel free to add a pull request with your set, but keep in mind that we'll probably be doing away with this format completely. We'll run a conversion on every level set we have (which is actually a lot) and probably host them for some sort of on-demand system.

**Comment by assertivist** [comment]
Let me know if you have any issues doing that. If you want you can send me the level set and I'll add it to our collection.
