### ISSUE TITLE
Fix sky shader head tracking

### ISSUE THREAD

**Issue by rherriman** [avaraline/Avara#4]
The sky shader reacts a bit too dramatically to head movement, leading to noticeably incorrect results.

<img width="1136" alt="sky-shader-head-tracking" src="https://user-images.githubusercontent.com/901522/45267432-5fe06380-b429-11e8-92a6-6d96a2b3c9f1.png">

**Comment by assertivist** [comment]
See the sky shaders in `shaders/`, `src/game/CWorldShader.cpp`, `src/bsp/CViewParameters.cpp` 

Especially `CWorldShader::ShadeWorld(CViewParameters *theView)`
