### ISSUE TITLE
Stalls/lock when starting games - "GatherPlayers" loop

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#44]
`CNetManager.cpp:483 GatherPlayers()`

This method gets called at the start of a network game to ensure all players are within `activePlayersDistribution`. To do this there is a `do/while` loop that runs the network `ProcessQueue` function until all players are ready or the `goAhead` flag is set by timeout (1800 ticks). 

For whatever reason this often fails in practice in internet games, sometimes completely locking all clients. There should probably be a way to reconcile which players are active faster, or restart the process to attempt to get the game started faster and/or avoid an error state.

**Comment by assertivist** [comment]
This might have been fixed by 5d9833784d693eef939ca3e5350c66a74f749879!

**Comment by tra** [comment]
We saw this happen tonight when 1 player left the game (or crashed?) and the host tried to start the game after the player left.  Perhaps this is a clue on how to reproduce it.

**Comment by assertivist** [comment]
@tra I have seen this maybe one time since we've added all these network fixes, and yeah it was because someone had crashed.
gonna close this one for now, i think we start games at least as well as the original at this point just through trying to fix the networking stuff generally
