### ISSUE TITLE
Score page of roster window - Post game scores packet

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#47]
The score page works locally--you can test it by playing a level single player, damaging yourself, taking note of your score, ending the game and then checking the score page.

The score page does NOT work when reporting the score from a network game. You can see how this works, right after you end a network game, if you are not the winner, BEFORE any other players exit the game, the score screen is accurate (from your local copy of the scores). 

But, as soon as the game ends or a player exits the game, they send the scores packet, and it is loaded into the local scores table. Something is wrong with this code, because the numbers get all crazy.

**Comment by rherriman** [comment]
Just wanted to comment that I suspect this is related to #10, and that either the scores packet is sent in big endian but not byte-swapped by the receiver(s), or the opposite.
