### ISSUE TITLE
Player ready/status functionality

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#49]
The original game had functionality where you could put the Avara application in the background and be excluded from consideration for inclusion in a new starting game, for example if you happened to step away for a few minutes. Other games could still start without considering you as a participant.

Rather than mess with cross-platform application focus, we can provide the same functionality with some kind of ready toggle button that appears on the roster after a level becomes loaded. This would only be on the local player's roster row, the other players would simply show the ready status, rather than a toggle button. It is probably possible to re-use the same flag that Avara used for being backgrounded to signal this over the network.

This indicator could also be used to absorb the purpose of the status line and provide more information with less text. I'm thinking of an icon for each player's status and ready selection, with perhaps the current status text descriptions and more info in a tooltip, for example ping or optional profile settings (location, realname)

**Comment by tra** [comment]
This is now possible with the addition of the `/away` text command.  It uses a loadingStatus flag of `kLAway`.
