### ISSUE TITLE
Load and use WAV (or preferably OGG) instead of HSND

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#51]
To do away with resource fork reading completely, we need to export all the sounds from HSND to a modern format (currently possible with hsnd2wav + other tools, which will be incorporated into the level converter).

But also Avara needs to be able to load and play those sounds into its own sound system. It should be possible to bypass the Huffman decoding step, add any necessary decoding of the chosen format (OGG or other) and give sample data directly to the sound mixer.

**Comment by dcwatson** [comment]
This was done as part of the big ALF merge - sounds are now OGG files, decoded into Avara's existing sound system.
