### ISSUE TITLE
Raise kMaxPlayers

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#53]
Avara's network architecture was developed for poor modem connections. With the vast availability of broadband, we should be able to handle a few more players than 6. This may need to wait until the frame rate is able to be increased and other network issues are flushed out.

**Comment by rherriman** [comment]
Other notes I want to make about the complications of raising kMaxPlayers: doing so may mean adding additional "teams" and team colors as well, or possibly even completely changing how teams and colors work. (Like allowing players to completely customize their color, assuming FFA by default, but having to assign teams via some new UI mechanism.)

**Comment by assertivist** [comment]
#101 closes this--turns out raising the limit is easy, we may run into issues in practice.

As @tra has mentioned, Avara makes `players * (players - 1)` connections between all the clients, and 56 connections is a lot of places to go wrong. 

To go any higher we will probably need to consider using the server packet routing method. I'm concerned that with the latency that adds, lockstep itself may become untenable. And changing lockstep to something else will be vastly complex, a little beyond the scope of what we're able to do realistically. There's still experiments to be done there, though.

At least we were able to add another two players, and with reasonable broadband or LAN connections, 8 players should work. We may even want to make a LAN or arcade/Avara appliance mode for the build that lets you go higher. 

As for internet play, going any farther than 8 might be a goal for a fork or sequel. In any case it would be a major refactor.
