### ISSUE TITLE
Team color adjustment/color-impaired accessibility

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#54]
The default team colors have been resurrected from 1996 and they look pretty bad. We should keep the general base colors so that references to team colors in level sets are still valid, but we can do better than #FF0000. 

Additionally, we should either add these team colors to be configurable in user preferences for local view only, or consider adding a color shift that makes the team colors distant enough for discernment among color-impaired users. 

Because we can't change colors of levels, or references to team colors, adding a text name of the team color to the roster interface is recommended (for example, if red is selected, the word "Red" is shown somewhere in the interface alongside it). This can allow a user to get the basic idea of what adjusted shade translates to which baseline team color, and makes team membership clearer overall.

**Comment by rherriman** [comment]
Current team and hull colors, for reference:

    #define kNeutralTeamColor 0x00ffffff
    #define kGreenTeamColor 0x00006600
    #define kYellowTeamColor 0x00cccc00
    #define kRedTeamColor 0x00cc0000
    #define kPinkTeamColor 0x00cc0099
    #define kPurpleTeamColor 0x009900cc
    #define kBlueTeamColor 0x000099cc
    #define kSpecialBlackColor 0x00303030
    #define kSpecialWhiteColor 0x00e0e0e0
