### ISSUE TITLE
Implement accurate lighting that honors level-specified values

### ISSUE THREAD

**Issue by rherriman** [avaraline/Avara#7]
From the Avara Level Design Manual:

```
  // Lights (default light settings are stored here)
  ambient = 0.4
  light[0].i = 0.4  light[0].a =  45  light[0].b = 20
  light[1].i = 0.3  light[1].a =  20  light[1].b = 200
  light[2].i = 0.0  light[2].a =  45  light[2].b = 90
  light[3].i = 0.0  light[3].a =  45  light[3].b = 180
```
> There are four posible light sources in addition to ambient light. To place a lightsource, give it an intensity (the i component) between 0 and 1.0. The two angles indicate the direction that the light is coming from. The b angle is the compass reading and the a angle is the angle from the horizon. All lights are monochromatic white.

`avara_frag.glsl` should be modified to handle multiple (configurable) directional light sources, and similarly allow the ambient light to be configurable.

![avara-3d-math](https://user-images.githubusercontent.com/901522/45307200-ab534a00-b4db-11e8-9dba-fc4c0128a2ee.png)

**Comment by assertivist** [comment]
* Geometry shader is in `shaders/`
* Shader is loaded in `util/AvaraGL.cpp` 
* The lighting configuration is loaded to `src/bsp/CViewParameters.cpp` (the `internalLight` structs)

**Comment by assertivist** [comment]
I was able to verify that the angles are coming over correctly. From my svg copy of grimoire:
```
light[0].i = 0.6
light[0].a = 60
light[0].b = 30
```

from the debug output:
```
INFO: LOADING LEVEL 1198680429 FROM classic-mix-up
INFO: Light from light table - idx: 0 i: 0.599991 a: 60.000000 b: 30.000000
INFO: Light from light table - idx: 1 i: 0.299988 a: 20.000000 b: 200.000000
...
```
I double-checked the parameters so I am feeling like this is as "correct" as we're going to get:

![grimoire_compare_take2](https://user-images.githubusercontent.com/1486313/57201324-a9e7fd80-6f54-11e9-89cb-30ad5967cabc.png)

Note the column still has a problem though! I had a brainwave and realized that this is a rotated block, and if the block had not been rotated, this lighting would be correct! The normals are set per-vertex for these OpenGL vertex arrays when we create the BSP object. BUT I checked and I can't find a place where the vertex normals get updated when something is rotated. We are just assuming that they are correct when the normals get passed to the shader for rendering. So I'm looking at ways to fix that now...

**Comment by assertivist** [comment]
Just realized that the above screenshot had ambient turned off, and Grimoire definitely sets a custom one. so here's an updated screenshot:

![grimoire_compare_take3](https://user-images.githubusercontent.com/1486313/57201539-5cb95b00-6f57-11e9-950b-c838cf133d1f.png)

**Comment by rherriman** [comment]
I wasn’t really thinking that the input values were incorrect, just that the directional lights generated from them were incorrect. But I don’t really understand shaders at all!

Interesting point about the rotated block normals... and lends an explanation as to why the ramps are screwed up, too: in Avara, ramps are really just blocks that are scaled and rotated into place. If you fix the issue, I am pretty confident the lighting will look completely correct.

**Comment by assertivist** [comment]
this is probably as close as we're going to get:
![image](https://user-images.githubusercontent.com/1486313/73129391-a0e60300-3f9f-11ea-8da0-609ecabda891.png)
