### ISSUE TITLE
Dome shading doesn't look right

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#81]
![image](https://user-images.githubusercontent.com/1486313/84580044-98e10100-ad90-11ea-8f8f-d77138bcec0e.png)
![image](https://user-images.githubusercontent.com/1486313/84580075-dd6c9c80-ad90-11ea-8e8d-d99d2900e68e.png)
![image](https://user-images.githubusercontent.com/1486313/84580066-caf26300-ad90-11ea-9056-98d46046813d.png)
❓ ❓ 
![image](https://user-images.githubusercontent.com/1486313/84580088-f2493000-ad90-11ea-8a3d-c076ad293277.png)

this could indicate the normals on the model being incorrect or a failure of the lighting shader

**Comment by rherriman** [comment]
Should probably check in OS9 to verify.

**Comment by assertivist** [comment]
fixed in #221
