### ISSUE TITLE
Windows installation instructions not working

### ISSUE THREAD

**Issue by culorsung** [avaraline/Avara#82]
After following the instructions, `make` won't run:

```
culle@LAPTOP-H0OVMH6B MSYS ~/Avara
# make
mkdir -p build/src/audio/
clang++ -Isrc/audio -Isrc/base -Isrc/bsp -Isrc/compat -Isrc/game -Isrc/gui -Isrc/level -Isrc/net -Isrc/util -Isrc/util/huffman -Ivendor/glad -Ivendor/nanovg -Ivendor/nanogui -Ivendor/pugixml -Ivendor -Ivendor -Ivendor/gtest/include -MMD -MP -g -Wno-multichar -DNANOGUI_GLAD -std=c++17 -c src/audio/CBasicSound.cpp -o build/src/audio/CBasicSound.cpp.o
make: clang++: No such file or directory
make: *** [Makefile:116: build/src/audio/CBasicSound.cpp.o] Error 127

culle@LAPTOP-H0OVMH6B MSYS ~/Avara
# make winapp
mkdir -p build/src/audio/
clang++ -Isrc/audio -Isrc/base -Isrc/bsp -Isrc/compat -Isrc/game -Isrc/gui -Isrc/level -Isrc/net -Isrc/util -Isrc/util/huffman -Ivendor/glad -Ivendor/nanovg -Ivendor/nanogui -Ivendor/pugixml -Ivendor -Ivendor -Ivendor/gtest/include -MMD -MP -g -Wno-multichar -DNANOGUI_GLAD -std=c++17 -c src/audio/CBasicSound.cpp -o build/src/audio/CBasicSound.cpp.o
make: clang++: No such file or directory
make: *** [Makefile:116: build/src/audio/CBasicSound.cpp.o] Error 127
```

Neither clang or clang++ are available under those names, although the makefile is looking for them:   
  
```
CC = clang
CXX = clang++
```

I've run the suggested pacman/dependency command. Running Windows 10 v1909. Let me know if I can provide anything else! Also interested in map design, I did some neat stuff with the original a long time ago and it'd be neat to see if someone out there still had any of it.

**Comment by culorsung** [comment]
Changing clang/clang++ to /mingw64/bin/clang and /mingw64/bin/clang++ seems to have resolved this issue.

**Comment by rherriman** [comment]
Glad you got it working. We could probably edit the README if this is a common problem, but I’m not sure we should bother—@assertivist is working on migrating the build system over to cmake, which I believe will remove the necessity for msys entirely.

Not sure what your question is re: map design. At the moment the old file format is (essentially) being used, though we are in active discussions on how to move away from it and convert existing levels to the new format. It is possible we have your set(s) somewhere in our archives, if you can provide us with more information!

**Comment by culorsung** [comment]
Thanks, I assumed so but figured I'd mention it in case someone else has the same problem.  
  
I don't recall level names, but there was definitely one with a nightclub theme to it, maybe something named perfecity?

**Comment by assertivist** [comment]
`clang` and `clang++` *should* be available under those paths if you install them with `pacman`. I often forget to restart the shell when I install stuff, any updates to your path won't take effect until you close and re-open the MSYS2 shell.
