### ISSUE TITLE
Slivers not colored correctly

### ISSUE THREAD

**Issue by assertivist** [avaraline/Avara#9]
Weapon slivers currently have incorrect colors included. Player slivers sometimes also have random yellow or red colors, this is either due to color replacement problems or the way that slivers gather a random color from the "exploding" shape.

![screenshot from 2018-09-10 11-02-33](https://user-images.githubusercontent.com/1486313/45312342-10616c80-b4e9-11e8-8121-fcdfc30f6b60.png)

Screenshot shows results from firing a grenade. Note that the player's walker colors have been included in the colors used for slivers.

**Comment by rherriman** [comment]
This should be resolved by #14, but we can reopen it if you disagree.
